# Podfile
use_frameworks!

target 'MySwiftDemo' do
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod "PromiseKit", "~> 6.0"
    pod 'PromiseKit/Alamofire'
    pod 'Firebase/Core'
end
